---
- name: mounting share(s)
  mount:
    path: /var/www
    src: fs-06a94046bc85a62be:/
    fstype: efs
    opts: nosuid,noexec,defaults,tls,accesspoint=fsap-08f4c19f3f712ee7d
    state: mounted


- import_tasks: setup-site.yml

- import_tasks: setup-db.yml