---
- name: mounting share(s)
  mount:
    path: /var/www
    src: fs-06a94046bc85a62be:/
    fstype: efs
    opts: nosuid,noexec,defaults,tls,accesspoint=fsap-07c2667e1055ea161
    state: mounted

- import_tasks: setup-site.yml

- import_tasks: setup-db.yml



























